[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
mint_nft = "3B1E88qLCVqEuSzx9ToZwEd9SjDT3ZnD1xv3tr6iSjeS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kiem.tran/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
